### ISSUE TITLE
Ver el número total de personas usuarias en SoundCollect.

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#13]
Esta información deberá actualizar cada vez que la persona usuaria ingresa al dashboard. 
Además, se debe mostrar la información segmentada por género y edad de las personas usuarias, usando las siguientes categorías:  

Género: 

- Mujeres
- Hombres
- No binario
- Otros
- Prefiero no decirlo

Edad:

- 18 años
- 18 -30 
- 30 -40 
- 40 -50 
- > 50 años

Incluir una nota al pie o ventana emergente en esta sección del dashboard donde se explican cómo se tratan los datos personales[ (términos y condiciones) ](https://docs.google.com/document/d/1BH4s3AnIwYIyKu6YFIsqz_2oPkwDduEc/edit?usp=drive_link&ouid=109059015259602155129&rtpof=true&sd=true) y compartir el enlace a la [política de privacidad.](https://docs.google.com/document/d/1Tx90Oo1ZLq4ah0IHobHOYJl07YJqpZDz/edit?usp=drive_link&ouid=109059015259602155129&rtpof=true&sd=true)

**Comment by TomasTubertSFC** [comment]
Después de reu con Johana 12/06 esos links que linken hacia la web de Soundcollect

**Comment by TomasTubertSFC** [comment]
@OtariOboladzeSfC Necesitaría que le asignaras un dominio a la página de SoundCollect http://3.76.139.141/ para hacer esto.

**Comment by TomasTubertSFC** [comment]
Está dando problemas. No entiendo tu comentario Oto. Un dominio no viene por defecto con SSL.

**Comment by OtariOboladzeSfC** [comment]
> Está dando problemas. No entiendo tu comentario Oto. Un dominio no viene por defecto con SSL.

ya esta solucionado, https funciona @TomasTubertSFC
