### ISSUE TITLE
Posible error en el proceso de validación de datos del dashboard. 

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/SoundCollect_dashboard#132]
@OtariOboladzeSfC @CarlosMillanSfC @almenarasfc @TomasTubertSFC 

No sé a quién corresponde este posible error. En el documento base se detalla la validación se pone los datos:
1) Datos de personas usuarias que hayan calibrado sus dispositivos móviles. 
2) Registros cuyos valores de LAeq estén entre 20dB - LAeq - 80dB. Fuera de este rango no se consideran erróneos, sino que simplemente son datos que no están caracterizando una área tranquila y por ende no se deben tomar en cuenta. 

Cuando veo los gráficos en el dashboard, veo valores de 110 dBA que no tiene congruencia cuando en teoría se han "descartado" los datos mayores a 80 dBA. Dudo que haciendo el promedio energético los valores se hayan subido tanto, no hay forma de encontrar promedios altos si en teoría no deben existir promedios con valores altos. 

<img width="829" alt="image" src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/83076037/90cd4a2b-a188-4878-96a5-3810d71b49ad">

Esto también me hace dudar de como se hizo el filtro para ver datos en el dashboard de las personas que han calibrado sus dispositivos móviles. Necesito poder comprobarlo también. Ya me dirán.

**Comment by TomasTubertSFC** [comment]
Para ver como hacer ese filtrado necesitaría saber si esto que comentas se ha de aplicar solo a la sección 3 o es un requerimiento para TODOS los datos del dashboard y por ende todas las secciones. 
@JohanaSfC

**Comment by JohanaSfC** [comment]
Tal como está en el documento base y como lo he comentado, es un requerimiento previo para ver los datos en el dashbaord, es decir, que aplica para TODOS los datos y por ende todas las secciones. 

Documento base: 
Los registros que se visualizarán en la plataforma de visualización deben pasar por un proceso de validación. Solo aquellos que cumplan con los siguientes dos requisitos serán visibles:
Datos de personas usuarias que hayan calibrado sus dispositivos móviles. 
Registros cuyos valores de LAeq estén entre 20dB LAeq  80dB. Fuera de este rango no se consideran erróneos, sino que simplemente son datos que no están caracterizando una área tranquila y por ende no se deben tomar en cuenta.

**Comment by TomasTubertSFC** [comment]
Perfecto. Gracias por la aclaración. @CarlosMillanSfC. Entonces, como consumo los datos desde el endpoint https://soundcollectapp.com/api/observations?with-levels=true para las tres secciones. Ya hago que el filtrado de esos datos sea desde el front.

**Comment by TomasTubertSFC** [comment]
Al llamar al endpoint  https://soundcollectapp.com/api/observations?with-levels=true ya se filtra en el front. Respecto al endpoint /observations/in-polygon que se utiliza de forma exclusiva en la sección 3 se filtrará en el backend.

**Comment by CarlosMillanSfC** [comment]
Agrego ese filtrado que dice Tomás, ahora cuando se llame al endpoint que filtra por polígonos este también tendrá en cuenta el valor de Leq para que sea entre 20 y 80, lo cual no tiene un gran impacto pero comento aquí:

Del total de observaciones que son:
mysql> select count(id) from observations;
+-----------+
| count(id) |
+-----------+
|       331 |
+-----------+

Reduce en 130 menos:
mysql> select count(id) from observations where Leq BETWEEN 20 AND 80;
+-----------+
| count(id) |
+-----------+
|       201 |
+-----------+
