### ISSUE TITLE
Incoherencias en las gráficas que depende de la selección del polígono - Sección 3 

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/SoundCollect_dashboard#133]
@almenarasfc @TomasTubertSFC @OtariOboladzeSfC @CarlosMillanSfC 

Hola, no me está cuadrando el número de registros que se pone en las gráficas. Es decir, selecciono este polígono, donde a ojo creo que hay entre 50 -60 registros. 

<img width="437" alt="image" src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/83076037/8bc72783-406f-4138-81ea-d01ec649898f">

Ahora esta gráfica pone que hay 147 observaciones, que claramente en el mapa no se ven tantas:

<img width="367" alt="image" src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/83076037/6efc79ec-da1a-41eb-acd7-85658ed76320">

En este gráfico, el valor más alto son 79 registros. ¿Que se hace con el resto de registros? Porque no se ven todos? 

<img width="897" alt="image" src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/83076037/dffc02d6-3b91-4cf3-82c9-09caa343f629">

Y en la última gráfica aparecen menos observaciones 

<img width="887" alt="image" src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/83076037/11d1750c-7fea-4bc0-8b1b-38d52f3c7611">

**Comment by almenarasfc** [comment]
@JohanaSfC, La gráfica "Tipos de sonido", esta corregida, pero no publicada, la he corregido durante el dia de hoy.

si hacemos un filtro sobre un area más pequeña y pocas observaciones podemos controlar mejor los resultados:

En esta selección abarcamos 6 observaciones:
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/7bde375e-a129-454e-b03c-9b1bb35d59eb)


En la primera gráfica recordemos que una observación puede tener mas de 1 tipo de sonido:
Amarillo 1 observación, verde 2, azul 6.
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/c453ec7a-f3e8-4235-a75c-be949113da5c)

Segunda gráfica, un total de 6:
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/83d4c6d6-b1af-4844-9743-09592e4a31ac)
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/aa230a23-d43c-4690-bc94-09b573c6ab66)

Tercera gráfica, cada barra es una observación, total 6:
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/fe54f631-e9d8-41b1-a8f0-5492ccbf70b7)


Como decía, estos test es mejor hacerlos con filtros que devuelva pocas observaciones, cuando son decenas es difícil determinar si algo falla. Hay que tener en cuenta que si el proceso se hace bien con 10 o 12 también se hará bien con 500.
