### ISSUE TITLE
Fix & Bugs 11/07/2024

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/SoundCollect_dashboard#163]
- [x] Revisión del gráfico cualitativo - ahora mismo la suma de las observaciones no suman en las diferentes variables. En tranquilidad suma un número que coincide con el total de observaciones que entran en el cono dibujado, pero en el resto de variables esa suma no coincide . Porfa, revisadlo a ver si hay algo que pueda estar fallando. 
- [x] octava. Actualmente este gráfico está moqueado. Hacedlo funcional aunque hayan pocos datos. Importante: el máximo de esta gráfica debe ser entre 120dB pero teniendo en cuenta que no entrarán datos mayores de 80dB (los datos que entran al dashboard deben tener un filtro de entre 20 y 80dB. Tal y como aparece en la primera página del documento base, todos los registros que estén fuera de este rango se consideran erróneos y por tanto no entran al dashboard.)
- [x] Trabajad para que al menos los gráficos que no tienen nombre en los ejes, lo tengan. El resto de cosas que pedía Johana lo podemos dejar para cuando acabemos esta iteración de cambios.

**Comment by almenarasfc** [comment]
Lo que hemos hablado en la daily:

Punto 1, asumiendo que se trata de los 4 donuts que hay en la sección "Descripció de la percepció del espai", (ya que creemos que en el mail se están mezclando gráficas y nomenclaturas) hay que aclarar con @JohanaSfC que es lo que se muestra en los donuts y que es lo que se esperaba ver. Respecto al número de observaciones que muestra las gráficas, ahora comprobare junto con Carlos si hay alguna inconsistencia con la BDD.

Hay que tener en cuenta que hay observaciones que ya nos llegan mal de back, deberían ser caracteres númericos y nos llega texto en algunas de ellas: 

![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/eb73928d-5690-4186-a151-557d28bc8bf0)


Punto 2, back debe facilitarnos los datos.

Punto 3, ya está hecho.

**Comment by almenarasfc** [comment]
@JohanaSfC El punto 1 está resuelto, con el problema que he comentado con @OtariOboladzeSfC 
Bailan 2 observaciones entre el donut de Tranquilidad y los otros 3. Eso se debe a que esas dos observaciones tienen los datos mal en cuanto a Tranquilidad, pero no en el resto de aspectos, con lo cual sí aparecen en las demás.

**Comment by TomasTubertSFC** [comment]
@OtariOboladzeSfC nos ha comentado que para la gráfica de 1/3 de octava moqueemos la información. Así lo hemos hecho y puesto en producción en la última PR #171.

Con esto, doy por finalizada esta issue
