### ISSUE TITLE
Modificar ejes X e Y

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#168]
Las palabras de los ejes de todos los gráficos deben ir en negrita y de un tamaño algo más grandes.

- [x] Evolució temporal sobre els nivells de so dB(A) en un període de temps
- [x] Visualització gradual dels nivells de so per hores
- [x] Tipus de so
- [x] Gràfica d'1/3 d'octava Sección 3
- [x] Descripció de la percepció del espai
- [x] Anàlisi de variables qualitatives - quantitatives
- [x] Dades qualitatives
- [x] Distribució de nivells de pressió sonora a l'àrea tranquil·la

- [x] Gráfico barras Sección 2 

- [x] Gràfica d'1/3 d'octava Popup Observación
- [x] Gráfica Nivell SPL continu equivalent Popup Observacion

**Comment by almenarasfc** [comment]
@JohanaSfC 


antes:
![Image](https://github.com/user-attachments/assets/2c0fc798-4dde-4352-b0b3-15845b2b0f15)

despues:
![Image](https://github.com/user-attachments/assets/ff74035c-ab4a-4c80-846f-814bc11fce78)
