### ISSUE TITLE
Visualización gradual de los niveles de sonido por horas

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#17]
La visualización se presenta como un círculo que representa un reloj, donde cada hora del día está marcada alrededor del perímetro.  En este reloj, el nivel de sonido se pinta de forma gradual (según escala) el nivel de sonido medio.  Los valores de los sonidos para cada hora, se calculan como el promedio de LAeq de todas las observaciones que existen en la zona de estudio seleccionado. 

Tienen que aparecer todas las horas del día.

<img src="https://github.com/ScienceForChange/sc_dashboard/assets/144031996/bc79e61e-7456-487c-ba3a-4dee5f000808" height=200 />
<img src="https://github.com/ScienceForChange/sc_dashboard/assets/144031996/c2799296-3854-45ec-a5b4-4d49f91ee052" height=500 />

**Comment by TomasTubertSFC** [comment]
Gráfico elegido por ICR

![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144031996/d3560698-0771-42ee-a7c4-4da7113d76d6)

https://echarts.apache.org/examples/en/editor.html?c=custom-polar-heatmap

**Comment by JohanaSfC** [comment]
Hola... puedes incluir las unidades en la escala. Debe aparecer en todos los valores, el número + "dBA". 
Incluye la leyenda de los colores en la parte superior o inferior del gráfico donde te quede mejor.

**Comment by almenarasfc** [comment]
@JohanaSfC 

![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/50566333-e14d-4f6f-86ea-16995f371e73)

![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/010a7de7-0348-4f8b-9e76-c8b2519073dd)

**Comment by JohanaSfC** [comment]
@almenarasfc puedes corregir de nuevo el texto es **"dBA"** y no dB(A). 
La leyenda la puedes colocar vertical a lado derecho de la gráfica. 
Y el título de la gráfica debe ser "Visualització gradual dels nivells de so per hores" ( utilice el traductor para colocarlo en CAT, por favor revisa que está bien escrito el título, sino please cámbialo. 
Gracias.

**Comment by almenarasfc** [comment]
@JohanaSfC 
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/593f0c66-2958-4740-89e1-8684a19d1f03)

**Comment by JohanaSfC** [comment]
Ok, cerrado! Gracias.
