### ISSUE TITLE
Evolución temporal sobre los niveles de sonido dB(A) en un periodo de tiempo

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#18]
El objetivo de esta visualización es observar y comparar la evolución de sonido de una zona registrada por las personas usuarias. Del área de estudio seleccionada se mostrará los datos LAeq por horas, Para esto se utilizará un tipo “gráfico de cajas y bigotes” , donde el eje X serán las 24 horas y el eje Y el nivel de presión sonora (dBA). Los colores de cada gráfico de cajas y bigotes dependerás si la hora está asociado a la categoría de día, noche o tarde. 
En esta gráfica también tendrá la opción de comparar dos series de datos. Es decir, la persona usuaria podrá seleccionar varios días, meses o años y ver el comportamiento. 
Las gráficas solo tendrán 3 colores.
Las gráficas se presentarán en el mismo gráfico. Se sobrepondrán unas a otras.

<img src="https://github.com/ScienceForChange/sc_dashboard/assets/144031996/677c99bd-4dae-4307-86c0-9d24a2cf4785" height=200 />
<img src="https://github.com/ScienceForChange/sc_dashboard/assets/144031996/c7d92a30-10a1-4064-970b-b868f0c825d3" height=200 />

**Comment by TomasTubertSFC** [comment]
El objetivo de esta visualización es observar y comparar la evolución de sonido de una zona registrada por las personas usuarias. Del área de estudio seleccionada se mostrará los datos para cada hora de valor del LAeq, L10, L90, Lmax y Lmin por horas, Para esto se utilizará un tipo “Candlestick” y cada diagrama de velas tendrá la siguiente información: 

Cada vez que el cursor pase por cada caja debe aparecer la información anterior y también el valor del LAeq. En conclusión debe seguir el siguiente orden: 
- LAeq
- L10
- L90
- Lmin
- Lmax

<img src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144031996/13110b68-2bbb-476c-a9f6-b40100cec07e" height=300/>

La gráfica, con todas las horas, se debe ver de la siguiente manera. Donde el eje X serán las 24 horas y el eje Y el nivel de presión sonora (dBA). El rango de horas que se debe usar es el mismo de la visualización gradual de los niveles de sonido por horas. 
Los colores de cada gráfico de velas dependerá si la hora está asociado a la categoría de día, noche o tarde.

<img src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144031996/79a1c373-1381-4d75-9f61-87a4019b0a56" height=400 />

La gráfica se podrá ver de una serie de datos en específica (tiempo seleccionado) o también se podrá comparar dos series de datos. Es decir, la persona usuaria podrá seleccionar varios días, meses o años y ver el comportamiento. 

<img src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144031996/5d2452f9-e346-486f-a1cd-371f89858803" height=400 />

**Comment by TomasTubertSFC** [comment]
Los rangos de horas se agrupan de la siguiente manera:
00:01 h - 01:00 h
01:01 h - 02:00 h
02:01 h - 03:00 h
03:01 h - 04:00 h
04:01 h - 05:00 h
05:01 h - 06:00 h
06:01 h - 07:00 h
07:01 h - 08:00 h
08:01 h - 09:00 h
09:01 h - 10:00 h
10:01 h -11:00 h
11:01 h - 12:00 h
12:01 h - 13:00 h
13:01 h - 14:00 h
14:01 h - 15:00 h
15:01 h - 16:00 h
16:01 h - 17:00 h
17:01 h - 18:00 h
18:01 h - 19:00 h
19:01 h - 20:00 h
20:01 h - 21:00 h
21:01 h - 22:00 h
22:01 h - 23:00 h
23:01 h - 00:00 h

**Comment by TomasTubertSFC** [comment]
Día: se refiere a aquellas observaciones registradas de 7:00 a 19:00, 
Tarde: es la franja horaria de 19:00 a 23:00 
Noche: entre las 23:00 a 7:00 a.m. del día siguiente.

**Comment by TomasTubertSFC** [comment]
- [ ] Al seleccionar los dos rangos de fechas, las gráficas se sobrepondran unas a otras. 
- [ ] Una de las series, debe tener un color más difuminado para poder diferenciarse. 
- [ ]  Al seleccionar con el cursor la vela, será cuando aparecerá el tooltip. 
- [ ] El tooltip debe indicar de que serie es la vela. 
- [ ] Las velas han de tener hover difuminando las demás.

**Comment by TomasTubertSFC** [comment]
@JohanaSfC Dime que qué tal para cerrar la issue.

![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144031996/be849140-39d1-4c38-82d6-c32755a9fada)
![ScDashboard-GoogleChrome2024-07-0209-54-54-ezgif com-video-to-gif-converter](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144031996/8bc9d6df-eaff-4144-a7f5-1c3b8596b1b1)

**Comment by JohanaSfC** [comment]
Hola @TomasTubertSFC dejo mis comentarios:

- En esta parte, cambie el nombre de "Serie 1" a  **"Sèrie de dades 1 "**.
¿Recuerda que todo debe estar en CAT. 

<img width="355" alt="image" src="https://github.com/ScienceForChange/SoundCollect_dashboard/assets/83076037/2bfd0711-8a03-4657-8485-0ab97db9c81f">

- Coloca la leyenda del gráfico así, una debajo de la otra creo que se puede entender mejor así. 
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/83076037/5230baa7-0a83-4eef-9657-c0b769b288ac)

- Incluye el nombre de los ejes en CAT. 
Eje X: Horas
Eje Y: Nivel de presión sonora (dBA)

**Comentarios generales:** Las tonalidades de los colores y el borde han funcionado, se pueden diferenciar mejor las dos series de datos. :)
Me gusta que se pueda seleccionar si quieres los datos solo del día de la serie 1 y de la serie 2.

**Comment by TomasTubertSFC** [comment]
![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144031996/68ccc125-85b6-40f2-b507-b264d66778d6)
