### ISSUE TITLE
Crear HomePage

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/SoundCollect_dashboard#190]

**Comment by almenarasfc** [comment]
Home creada, esperando contenido.

**Comment by JohanaSfC** [comment]
@almenarasfc puedes ir incluyendo el contenido que hay en el footer de la págian web de SoundCollect , en la home del dashboard. 

Es decir esta ifnormación: 

<img width="927" alt="image" src="https://github.com/user-attachments/assets/329b06ab-1c47-4ac0-9287-2da236dbece9">

Colocarla aquí:

<img width="975" alt="image" src="https://github.com/user-attachments/assets/8c778413-53ac-4fa4-b581-aa926f97ddb2">

@TomasTubertSFC te puede decir donde están todos los logos, los tendrá a mano. 

Gracias.
