### ISSUE TITLE
Fix/Bugs 17(07/2024 (ICR)

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/SoundCollect_dashboard#198]
@almenarasfc @TomasTubertSFC 

Dejo aquí un par de comentarios que ha dejado ICR sobre el dashboard y se deben implementar.

- [x] #202

<img width="956" alt="image" src="https://github.com/user-attachments/assets/f62e7b4b-c9e7-459b-a320-bace5e2a9a01">

- [x] En todos los gráficos de 1/3 de octava (en el desplegable que se abre de ca observación y en la gráfica de la sección de paseo sonoro) se debe cambiar la leyenda. Ahora dice "Con ponderación" y debe decir "Ponderación A"

<img width="848" alt="image" src="https://github.com/user-attachments/assets/65bc7bf4-7f9c-488a-a189-e100a9575f73">

- [x] Cambiar el nombre del titulo de la sección 3. Ahora dice paisajes sonoros y debe ser "Análisis" 
- [x] Cambo iconos de las secciones: 

Sección de resumen: Colocar este icono o uno similar. 
<img width="223" alt="image" src="https://github.com/user-attachments/assets/d2ea066f-4b6e-4fa6-93d1-7206c9021535">

Link flaticon: https://www.flaticon.es/icono-gratis/resumen_4693900?term=resumen&page=1&position=32&origin=search&related_id=4693900

Sección Análisis:  
<img width="227" alt="image" src="https://github.com/user-attachments/assets/7fdce500-90b3-4a5b-8cf1-99aec50d3626">
Link: https://www.flaticon.es/icono-gratis/investigacion-de-mercado_6019623?term=analisis&page=1&position=69&origin=search&related_id=6019623

**Comment by almenarasfc** [comment]
@JohanaSfC  respecto a los iconos yo trataría de utilizar los que vienen en el framework con el que trabajamos para el dashboard, por tratar de mantener una coherencia en la estética todo proyecto y porque en tamaños pequeños (como es el caso) es mejor utilizar iconos más simples.
[Iconos PrimeNG](https://primeng.org/icons)

**Iconos como estos para representar la sección de gráficos (Análisis)** 
![image](https://github.com/user-attachments/assets/9f4626ad-49cf-4251-8380-a4eed2731504)



**Y estos para Resumen**
![image](https://github.com/user-attachments/assets/985f08a2-388d-4a2e-a84b-c30b6025d06e)
![image](https://github.com/user-attachments/assets/9aff1b91-b0ad-4e6a-8b9a-04dc633b6494)

**Comment by JohanaSfC** [comment]
Excelente Alberto, tienes razón y no sabía que el framework tenía esto. Te selecciono los iconos que irían:

<img width="377" alt="image" src="https://github.com/user-attachments/assets/3c8ff78e-c2ed-4427-9442-0dcd8d00a406">

**Comment by JohanaSfC** [comment]
Hola @almenarasfc @TomasTubertSFC 
Pueden corregir esto de nuevo.

Todas las leyendas de la banda de 1/3 de octava deben cambiar de "Amb ponderació" a "dBA" y de "Sense ponderació" a "dB", y la etiqueta del eje Y debe cambiar de "Pressió sonora dB" a "Pressió sonora".

**Comment by TomasTubertSFC** [comment]
Para mantener la funcionalidad ya creada, en el eje Y, hacemos que cuando se cambia en la leyenda el eje Y pase de Pressió sonora a Pressió sonora dBA.

**Comment by TomasTubertSFC** [comment]
![Grabacin2024-07-22095830-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/f03152c2-08a3-4757-a7db-546daae20f8b)

**Comment by JohanaSfC** [comment]
Hola, vuelve a corregir la leyenda de la gráfica es dBA en mayúscula la letra A.

**Comment by TomasTubertSFC** [comment]
Hecho #236
