### ISSUE TITLE
Gráfico de 1/3 de octava

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#21]
El objetivo de la gráfica es observar el tipo de frecuencias tonales que se han ido registrando en la zona de estudio e identificar los bajos y los altos.  De este modo se puede identificar si hay más peso en baja frecuencia o en alta frecuencias. 
El eje X corresponde a las frecuencias (Hertz) y el eje Y corresponde al nivel presión sonora dB.  El gráfico se puede seleccionar, ver el nivel de presión sonora sin ponderación (Leq) o con ponderación A (LAeq). 
Los límites de eje X están entre 50- 16.000 Hertz y el eje Y se configura de manera escalable siendo 0 el mínimo y el máximo = Lmax del área tranquila + 20dB, 
<img src="https://github.com/ScienceForChange/sc_dashboard/assets/144031996/c10d066b-26c8-4ef3-aedf-432d32286173" height=300 />

**Comment by almenarasfc** [comment]
@JohanaSfC :


![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/a8128313-7e5d-43be-9873-02c30aab42e3)

![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/addf814d-40eb-40a2-abd4-b250d54377f6)

![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/8cefff69-b110-48de-bbfd-baa76e454e9e)

**Comment by TomasTubertSFC** [comment]
Paso esta issue a la nueva #240
