### ISSUE TITLE
Descripción de percepción del espacio

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#23]
Sé utilizará el tipo de gráfico “donut” para representar la valoración que han registrado las personas usuarias. Se tomarán los datos de las preguntas de las encuestas, es decir, se tendrán un gráfico de donut para la tranquilidad, limpieza y mantenimiento, accesibilidad y seguridad. 

Tranquilidad:
- Nada tranquilo
- Poco tranquilo
- Moderadamente tranquilo
- Bastante tranquilo
- Muy tranquilo

Limpieza y el mantenimiento:
- Muy malo
- Malo
- Regular
- Bueno
- Muy bueno

Accesibilidad:
- Muy mala
- Mala
- Regular
- Buena
- Muy buena

Seguridad:
- Muy mala
- Mala
- Regular
- Buena
- Muy buena

- [x] Datos Tranquilidad
- [x] Gráfica Tranquilidad
- [ ] Datos Limpieza y mantenimiento
- [x] Gráfica Limpieza y mantenimiento
- [ ] Datos Accesibilidad
- [x] Gráfica Accesibilidad
- [ ] Datos seguridad
- [x] Gráfica Seguridad

**Comment by almenarasfc** [comment]
@OtariOboladzeSfC 
Al igual que pasaba con la gráfica de "Tranquilidad" en este caso también llegan todos los datos como texto:

 "cleanliness": "Regular",
 "accessibility": "Dolenta",
 "safety": "Regular",

deberían llegar como numérico a poder ser o en un solo idioma.

**Comment by almenarasfc** [comment]
@OtariOboladzeSfC 
@CarlosMillanSfC 
este tema como lo tenemos?
