### ISSUE TITLE
Nuevas observaciones generar error al abrir en el mapa

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/SoundCollect_dashboard#238]
Hola @TomasTubertSFC he mirado en el dashboard que las nuevas  observaciones realizadas con la versión V1.0.3 de la app, no se pueden visualizar en el dashboard. 
Es decir, si aparecen en el mapa, pero cuando le doy clic en la observación y aparece el desplegable sale este error.  Y la gráfica de LAeq,t no carga. 

<img width="949" alt="image" src="https://github.com/user-attachments/assets/6e715ab1-300d-4f9b-aeae-375fe24b66fd">

Puedes ver que pasa y arreglarlo.

**Comment by TomasTubertSFC** [comment]
LAeqT: Array de numero
![image](https://github.com/user-attachments/assets/0a83a378-2853-4754-ae00-5b3c00589b37)
LAeqT: string
![image](https://github.com/user-attachments/assets/30263801-35ba-4950-9c34-144be5160228)
@JohanaSfC Gracias por darte cuenta!

@OtariOboladzeSfC ha cambiado el tipo de dato de las observaciones y no me ha avisado, pero solo de las nuevas. El código estaba preparado para la segundo tipo de dato, string o texto y por eso rompe. Ya que texto y array no tienen los mismos métodos.

Para poder solucionarlo, he de acordar con @OtariOboladzeSfC que tipo de dato va a llegar para modificar el código.

**Comment by TomasTubertSFC** [comment]
Ayer hablé con @OtariOboladzeSfC sobre esto. Me comentó que no es prioritario validar como la app envia esos datos al Backend  manteniendo este problema. La solución propuesta por él es modificar los datos existentes en la base de datos para que sean iguales.

**Comment by TomasTubertSFC** [comment]
Finalmente esto lo he actualizado en la PR #258  y compruebo que tipo es en el front. Algo que no es muy buena práctica. Cuando se pueda que se limpie el backend y la base de datos. Así que mientras, dejo esta issue cerrada.
