### ISSUE TITLE
Error en registro de la hora de las observaciones 

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/SoundCollect_dashboard#239]
Hola @TomasTubertSFC como se corrigió en la aplicación el tema del desfase horario que existía entre la fecha creada y la que se guarde en el servidor.

@OtariOboladzeSfC me dice que debes actualizar el campo de la fecha.  Aquí te pondrá la información.

**Comment by OtariOboladzeSfC** [comment]
hay que usar "user_local_time" en lugar de "created_at"

**Comment by TomasTubertSFC** [comment]
user_local_time está como null en todas las observaciones: @OtariOboladzeSfC 
![image](https://github.com/user-attachments/assets/7d6fb91b-3163-46f5-a126-9baff4a1a82e)

**Comment by TomasTubertSFC** [comment]
Esta issue queda cerrada hasta que se solucione lo mencionado en el comentario de arriba. @OtariOboladzeSfC @JohanaSfC
