### ISSUE TITLE
Análisis de las preguntas abiertas

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#24]
Para los datos de las preguntas abiertas se representarán con una “nube de palabras”. Se tendrán una nube de palabras para la pregunta: “¿Si pudieras aplicar alguna medida para proteger acústicamente este espacio, que propondrías?”

![image](https://github.com/ScienceForChange/sc_dashboard/assets/144031996/76c9c9be-8c3e-4062-a60d-bba927d1a265)

**Comment by almenarasfc** [comment]
@OtariOboladzeSfC 
@JohanaSfC 

necesitamos saber de donde saldrán las palabras. No encuentro referencia a esto en al documentación. Gracias.

**Comment by OtariOboladzeSfC** [comment]
la ultima cuestión en el app es esto:

![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/116548840/48734b2d-bd23-4ce2-88cd-e0f1425a846a)

solo el campo 'protection' tiene que servir como fuente de las palabras:

![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/116548840/0c1fe5c6-7f48-48fb-9dd4-4721718f9226)

@almenarasfc

**Comment by almenarasfc** [comment]
@OtariOboladzeSfC entiendo que este campo es libre? pueden escribir lo que quieran?

**Comment by OtariOboladzeSfC** [comment]
Sí,  y también un detalle: los textos están escritos en diferentes idiomas

**Comment by almenarasfc** [comment]
@JohanaSfC 
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/645758e4-e733-4bc7-8311-b360a21a7e6c)
