### ISSUE TITLE
Zonas de estudio

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/SoundCollect_dashboard#273]
**FRONT:**
- [x] #279
- [x] Mapa y dibujado de polígono
- [x] #281
- [x] Formulario de participantes con logotipo
- [x] Listado Zonas de estudio
- [x] SoftDelete ¿y borrado? de zonas de estudio.
- [x] Editar Zona de estudio
- [x] #287
- [x] Crear popup con información sobre la zona en mapa colaborativo

**BACK:**
- [x] #277
- [x] Endpoint crear ZE
- [x] Endpoint index ZE
- [x] Endpoint update ZE
- [x] ¿Endpoint delete ZE?
- [x] Añadir función de habilitar

**BUGS**
https://github.com/ScienceForChange/SoundCollect_dashboard/issues/273#issuecomment-2332164243

**Comment by almenarasfc** [comment]
No he podido hacer push de ningún cambio en Backend debido que no tengo permisos.

**Comment by TomasTubertSFC** [comment]
ENDPOINTS:

listado : /api/admin-panel/study-zone
show: /api/admin-panel/study-zone/1
store: /api/admin-panel/study-zone
update: /api/admin-panel/study-zone/1
delete: /api/admin-panel/study-zone/1

**Comment by almenarasfc** [comment]
**BUGS BACK**

- [ ] El campo conclusión no debe ser obligatorio
- [ ] El endpoint del filtro de polígono debe aceptar fecha de inicio y fin

**Comment by TomasTubertSFC** [comment]
- [ ] Evitar que más de una zona de estudio sea visible en los mapas
