### ISSUE TITLE
Exportar datos

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#28]
Esta funcionalidad permitirá descargar dos archivos del área de estudio seleccionada. 

- [x] #270
- [x] Descarga de archivo en formato GPKG
- [x] Descarga de archivo en formato KMZ

**Comment by almenarasfc** [comment]
![Image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/de736053-8f89-4668-a85a-01f309b8d65b)

**Comment by almenarasfc** [comment]
@OtariOboladzeSfC 
@CarlosMillanSfC 

Faltan endpoints de descarga

**Comment by TomasTubertSFC** [comment]
El primer endpoint desde back, se realizó con un POST para poder enviarle los mismos datos del enpoint ya creado del filtrado de observaciones /observations/in-polygon. El problema, es que devolvía un texto plano. Un formato, que rompe. Se podría devolver un texto en formato JSON para que el front puediera gestionar la descarga.

Respuesta del endpoint de la app de odour con un formato válido.
![image (2)](https://github.com/user-attachments/assets/1cf565cb-8695-431c-82f3-9aca039dad66)

Respuesta del endpoint:
![image (3)](https://github.com/user-attachments/assets/8085002c-3286-4113-a1ed-21a545034e60)

Ante este problema. @OtariOboladzeSfC decide cambiar el tipo de endpoint a GET para ver si encontraba una solución. El problema con esto, es la codificación de la URL. Back consigue realizar la descarga de datos con un URL que no sigue los estándares de codificación:

Formato de url que back necesita:
https://soundcollectapp.com/api/download_observations?polygon=["2.0214844 41.545589", "1.8292236 41.1538424", "2.4581909 41.2798705", "2.0214844 41.545589"].

Después de la reunión de hoy, @OtariOboladzeSfC comenta que no puede hacer más y que poder solucionar esta tarea recae en que el front pueda gestionar esa codificación.

**Comment by TomasTubertSFC** [comment]
Habrá realizar la descarga de los archivos desde Frontend. Algo que no es buena práctica.

**Comment by TomasTubertSFC** [comment]
Habrá que hablar con Eduard de que información de las observaciones querrá en el csv.

**Comment by TomasTubertSFC** [comment]
Ahora, viendo como poder crear el archivo en GPKG he encontrado este comentario y librería:

This library comes at a whopping 12.4MB, and it also breaks minification efforts in Webpack. As a result, I would not suggest using this in a producton application. If you have to, you would be better off creating an API endpoint or lambda action that carries out the conversion on the backend using tried tools such as GDAL. 

https://www.npmjs.com/package/@ngageoint/geopackage

Aun así, estoy teniendo problemas con Webassembly.

**Comment by TomasTubertSFC** [comment]
Para los archivos KML que son para google earth o google maps entre otros, ya lo he podido implementar desde el front.
![image](https://github.com/user-attachments/assets/c1947205-9b1f-474f-a6f8-cabc26195626)

Se le pueden añadir más propiedades. @JohanaSfC

**Comment by TomasTubertSFC** [comment]
Lo que hay que modificar del archivo KML es el orden. Poniendo primero el Leq y cambiarle el nombre a LAeq.

- [ ] Cambiar nombre y orden.

**Comment by TomasTubertSFC** [comment]
Para seguir con la descarga de CSV he creado una issue aparte: #270

**Comment by TomasTubertSFC** [comment]
![image](https://github.com/user-attachments/assets/101badf0-f1ef-46a0-ae72-facad5eb043a)
Actualizado archivo kml
