### ISSUE TITLE
Filtrar por tipos de personas usuarias.

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_dashboard#30]
Filtrar por tipos de personas usuarias. Este filtro tendrá las categorías que se usan en la gamificación, es decir: 
Contribuyente
Ciudadano/a acústico/a
Explorador/a acústico/a
Viajero/a sonoro/a
Informador/a experto/a.

Hay que implementar la lógica de usuario experto en el back-end.

**Comment by CarlosMillanSfC** [comment]
Agrego este documento que es importante:

https://docs.google.com/document/d/1JIFflHnbWOXS4FcMta-ZuBiKqobn3Ts2XTi54jUO8Io/edit

**Comment by OtariOboladzeSfC** [comment]
> Agrego este documento que es importante:
> 
> https://docs.google.com/document/d/1JIFflHnbWOXS4FcMta-ZuBiKqobn3Ts2XTi54jUO8Io/edit

Es toda la info que hay alrededor de gamificación

**Comment by CarlosMillanSfC** [comment]
En odourCollect usamos un middleware para que compruebe la gamificación dell usuario.

https://github.com/ScienceForChange/odourCollect_2.0/blob/fe441f0bdebf494e86a64d9b49bd633ff56442fc/api/app/Http/Middleware/CheckGamificationLevel.php

que lo que hace es comprobar las observaciones del usuario loggeado y le actualiza la columna nivel, la cual siempre hace referencia al nivel máximo conseguido (ya que nunca baja, solo sube) y entonces así evita enviar repetidamente el aviso de "lvlUp" si ha borrado observaciones mostrando la última "medalla" conseguida.

**Comment by CarlosMillanSfC** [comment]
@OtariOboladzeSfC he preguntado esto muchas veces pero lo pregunto una última vez por aquí: hay posibilidad de tener acceso al código de qualud? me refiero a donde ellos calculan la gamificación ya directamente para usarlo de guía.

Gracias.

**Comment by OtariOboladzeSfC** [comment]
@CarlosMillanSfC en algun lugar en estos ficheros se calculan la gamificacion
@TomasTubertSFC @Almenara nos podéis echar un vistazo? es un codigo de Ionic/Angular

**Comment by CarlosMillanSfC** [comment]
parece que es aquí:

https://github.com/ScienceForChange/SoundCollect_frontend/blob/2232722258f77046d48cd94ca5f3930bbfabba56/src/app/services/user-service.ts#L71

**Comment by CarlosMillanSfC** [comment]
Bueno, teniendo la lógica que aplica qualud en la app la he adaptado para que el servidor calcule el nivel de los usuarios de la misma manera y así evitar inconsistencias (en el back no es muy eficiente hacerlo de esa manera pero para tener el filtro funcionando y asegurado que es igual que en el front vale, crearé tarea para cubrir deuda técnica y linkaré esta issue)

Como el endpoint que se utiliza es: https://soundcollectapp.com/api/observations

**Comment by CarlosMillanSfC** [comment]
@TomasTubertSFC Cuando vayas a implementar el filtrado utilizando este dato me comentas con cualquier problema que tengas y lo dejamos solucionado 👍
