### ISSUE TITLE
Cleanup user "path"

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_dashboard#33]
Cleanup user "path".

"Path" need to be updates for old observations that did hot have it.

**Comment by TomasTubertSFC** [comment]
¿Cómo designamos los colores a cada path?
`"path": "[{lat:1.2, lon:3.4}, {lat:5.6, lon:7.8}]"`
Necesitaríamos que de cada segmento del path, tengamos más información.

**Comment by OtariOboladzeSfC** [comment]
este JSON se modificará para tener mas parámetros dentro, incluso el LAeq.
Actualizaré los docs con la esto
