### ISSUE TITLE
Zonas de estudio

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/SoundCollect_dashboard#347]
![Image](https://github.com/user-attachments/assets/c5432197-c615-4ccc-8ce9-cd02304be91f)
Crec recordar que quan vam parlar d’introduir aquestes zones d’estudi, on el visor et porta directament a una àrea delimitada. Es va parlar de poder introduir una imatge i un text descriptiu, entendria que quan a partir del desplegable de les zones d’estudi, es clica a Manresa (p.e.) sortís un desplegable just a sota, on hi hagués un text i una imatge, en aquest cas podria ser quelcom com:

![Image](https://github.com/user-attachments/assets/ef012132-7e93-49cd-8334-cfae7b5f9560)

(és un exemple i diferents formules són possibles, això evidentment seria funció de l’administrador que tingués la possibilitat de no posar res, posar sols un text o posar títol, text i una imatge)
Penseu que aquests estudis en detall estaran lligats o projectes concrets: Un ajuntament que participa en la #SSSoroll, un centre escolar que fa una activitat de l’APS durant el curs escolar 24-25 o un taller de contaminació acústica amb un determinat col·lectiu, i per tant, té un sentit posar-hi un identificador propi al conjunt de registres.
- Escalabilitat dels registres en el mapa. Penso en alguna manera de visualitzar els registres d’una manera més vistosa . Ara mateix amb el mapa de Catalunya, s’intueix dades a Manresa i a Barcelona, enlloc més, has de fer un zoom.

![Image](https://github.com/user-attachments/assets/8dba9196-6a72-43fe-ac11-d4f93533dd1d)

No es podria fer que sortissin tots els punts des d’un bon inici i que en funció del zoom anessin escalant-se les seves dimensions? Fins i tot, i això crec que també ho havíem parlat inicialment en la fase de disseny, de que sortissin uns gomets amb la quantitat de registres que hi ha, quan estem parlant d’escales molt grans i a mesura de que vas reduint escala, es millora la visualització. Us vaig passar un parell de webs que treballaven d’aquesta manera:

https://map.silencio.store/
https://deandar.com
https://noise-planet.org/map_noisecapture/index.html#13/41.3738/2.0950/

- Carrega de registres. He estat fent proves i m’estic trobant que moltes capes que seria interessant carregar, no les puc carregar per la limitació de ‘arxiu a carregar. (Arxiu de dimensions màximes 9,5 M). Aquesta és una limitació real de la plataforma o l’he posat vosaltres per no carregar excessivament el sistema?

![Image](https://github.com/user-attachments/assets/c093ac2a-aa8d-49d2-abd5-247b5b17ff81)

A més el missatge quan surt, deforma el disseny del menú. Aquest missatge no podria sortir just a sota del menú d’opcions (botons en taronja). I el missatge de l’error pot ser en català o en l’idioma que correspongui en funció de l’idioma escollit per l’usuari?

```
Nota: Jugant una mica amb el QGIS he vist que pots obtenir les capes amb extensió
GGS i QGZ i ocupen bastant menys, potser serà la solució jugar importar altres
tipus de fitxers... La meva companya especialista en tema GIS la tinc de vacances
i veig que aquest punt no el podrem acabar de tancar, jo no tinc prou coneixement
del tema
```

- Informació el registre en pantalla inicial
En la pantalla inicial amb els punts del mapa, puc clicar a qualsevol registre i veure
les dades, perfecte, però accedeixes a una pantalla amb el detall de l’observació,
però no surt:
- Foto o fotos fetes
- Dades psicoacústiques
- Dades del qüestionari
Això està fet a posta, de només mostrar part d’informació del registre?

![Image](https://github.com/user-attachments/assets/929a3b91-29ef-4cd3-8d53-4a7985568df0)

Ara m’adono que per descriure els valors mesurats es fa referència al àudio registrat no sé si és el més adient, en tot cas i seguint el mateix criteri potser s’haruia de posar Informació dels nivells mesurats.
En tot cas igual que hi ha a l’app, el paràmetre principal és el LAeq i el posaríem en primer terme. I els L10 i L90 es posaria LA10 i LA90

Més avall del menú hi ha l’espectre en 1/3 octava:

![Image](https://github.com/user-attachments/assets/bb253b87-3c14-4542-a941-5d0a00e88d48)

El títol del gràfic hauria de ser Distribució espectral en 1/3 d’octava o Espectre en 1/3 d’octava 
En aquest mateix gràfic manquen els càlculs de les tres darreres columnes: LAeq, LCeq i LZeq
També en aquest mateix gràfic el dB cal canviar-ho per dBZ.
Sobre aquest mateix gràfic quan et poses sobre les bandes, surten uns carros de decimals enormes, sempre hem dit de treballar coma a molt amb un decimal.

![Image](https://github.com/user-attachments/assets/1b7c54cf-5add-431d-a841-1c546e31b3d0)

```
Això es va parlar amb ICR. Les dades acústiques com LAeq, espectres, etc... sols 1 decimal.
Només té sentit incrementar el número de decimals en les dades quantificables de les dades piscoacústiques. Consultar ICR.
```

**Comment by almenarasfc** [comment]
- [ ] Mostrar información sobre las zonas de estudio (se muestran clicando sobre el poligono)
- [ ] Al hacer zoomout se dejan de ver los registros. (clusters?)
- [ ] Probar a cargar archivos GPKG y KML mucho mas pesados, preguntar qeu suelen pesar estos archivos.
- [ ] El mensaje de error al no poder cargar el archivo desmonta la maquetación
- [ ] archivos GGS i QGZ?
- [ ] Revisar orden y datos a mostrar en la info de la observación @JohanaSfC 
- [ ] 1/3 8ª cambiar titulos
- [ ] 1/3 8ª faltan datos @JohanaSfC 
- [ ] 1/3 8ª Los datos con un solo decimal

**Comment by almenarasfc** [comment]
Clusters añadidos en ambos mapas:
![Image](https://github.com/user-attachments/assets/955fb716-26ee-48e6-8640-b2d21d64f79a)

**Comment by JohanaSfC** [comment]
@almenarasfc tal como te comente en este issue #348 se debe hacer cambios en el nuevo gráfico de datos. 
Ahí también coloqué la información de título y la descripción.

**Comment by almenarasfc** [comment]
@JohanaSfC 
he estado informándome sobre los archivos tipo GGS y QGZ. Estos archivos parece que se utilizan con el programa QGIS, al que Eduard hace referencia, pero no parece ser un tipo de archivo común sino más bien propio de QGIS y no he encontrado mucha información de como tratar con ellos para añadirlos a Mapbox. (de los tipos GGS no he encontrado nada que haga referencia a mapas)
