### ISSUE TITLE
CI pipeline para frontend en Github Actioins

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_dashboard#39]

**Comment by CarlosMillanSfC** [comment]
He agregado un job en github actions para que cuando se haga una PR a Master esta desencadene en un proceso que haga builds de las imágenes de docker para frontend y se creen en el servidor de producción.

Actualmente no hay tests en el proyecto pero he mantenido esa parte del proceso para que cuando se creen los tests sea fácil incluirlos.
