### ISSUE TITLE
weather API

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_dashboard#51]

**Comment by OtariOboladzeSfC** [comment]
https://github.com/ScienceForChange/SoundCollect_backend/blob/e33f5297d35690ba190dcd1b692a0561db346745/api/app/Http/Controllers/ObservationController.php#L71

falla llamada a API endpoint, he desactivado 4 líneas temporalmente pero hay que investigar que falla.

@CarlosMillanSfC

**Comment by CarlosMillanSfC** [comment]
To be fair idk what I did cos the .pem key has nothing to do with the openweather api calls but now its working as I can see checking the lasts registers in the observations table:

| Field                   | Value                                                         |
|-------------------------|---------------------------------------------------------------|
| id                      | 9c50b213-1cbf-4ece-9988-b1c64e991365                          |
| Leq                     | undefined                                                     |
| LAeqT                   | "undefined"                                                   |
| LAmax                   | undefined                                                     |
| LAmin                   | undefined                                                     |
| L90                     | undefined                                                     |
| L10                     | undefined                                                     |
| sharpness_S             | undefined                                                     |
| loudness_N              | undefined                                                     |
| roughtness_R            | undefined                                                     |
| fluctuation_strength_F  | undefined                                                     |
| images                  | NULL                                                          |
| longitude               | 2.15119                                                       |
| latitude                | 41.37761                                                      |
| quiet                   | Moderadament tranquil                                         |
| cleanliness             | Dolent                                                        |
| accessibility           | Dolenta                                                       |
| safety                  | Bona                                                          |
| influence               | Fff                                                           |
| landmark                | question_removed                                              |
| protection              | Fddb                                                          |
| user_id                 | 9bd685aa-62f6-461a-8b39-8ddacc6e6fbe                          |
| created_at              | 2024-06-18 09:46:29                                           |
| updated_at              | 2024-06-18 09:46:29                                           |
| deleted_at              | NULL                                                          |
| **temperature**             | 26.51                                                         |
| **pressure**                | 1013                                                          |
| **humidity**                | 52                                                            |
| **wind_speed**              | 6.69                                                          |
| pleasant                | NULL                                                          |
| chaotic                 | NULL                                                          |
| vibrant                 | NULL                                                          |
| uneventful              | NULL                                                          |
| calm                    | NULL                                                          |
| annoying                | NULL                                                          |
| eventfull               | NULL                                                          |
| monotonous              | NULL                                                          |
| overall                 | NULL                                                          |
| path                    | [{"lat":41.3776066,"lng":2.1511872}]                           |

9bd685aa-62f6-461a-8b39-8ddacc6e6fbe -> is my user id

**Comment by OtariOboladzeSfC** [comment]
weird, I see indeed that there were weather API calls correctly bringing values into the database, but now it does not work again and I cannot see git version when it was working properly
