### ISSUE TITLE
Remote key problem

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_dashboard#52]
When connecting from Laravel to Flask, new romte key doesnot work.

not even changing .env file on the server and not even .env from within the container

Quick fix right now is to update config/filesystem.php driver and put private key directly into it

**Comment by CarlosMillanSfC** [comment]
I think its mostly a type in the docker-compose.prod.yml file:
     [-] - /usr/src/flask_key_pair.pem:/usr/src/flask_key_pair.pem
     [+] - ./flask_key/flask_2cpu_private_key.pem:/usr/src/flask_key/flask_key_pair.pem

Then is not getting the correct flask_key_pair.pem. Ill change it and see

**Comment by CarlosMillanSfC** [comment]
I see that the communication is available again cos the data is being populated:

| Field                   | Value                                                                                                                                        |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------------------|
| id                      | 9c50c8c6-6b45-4523-be51-9f1bdf65d735                                                                                                         |
| **Leq**                     | 71.18                                                                                                                                        |
| **LAeqT**                   | "40.19,44.29,77.25,67.92,67.95"                                                                                                              |
| **LAmax**                   | 77.25                                                                                                                                        |
| **LAmin**                   | 40.19                                                                                                                                        |
| **L90**                     | 40.19                                                                                                                                        |
| **L10**                     | 77.25                                                                                                                                        |
| sharpness_S             | null                                                                                                                                         |
| loudness_N              | null                                                                                                                                         |
| roughtness_R            | null                                                                                                                                         |
| fluctuation_strength_F  | null                                                                                                                                         |
| images                  | ["https://soundcollectbucket.s3.eu-central-1.amazonaws.com/users/9bd685aa-62f6-461a-8b39-8ddacc6e6fbe/3sneCpwgbhJHzYjh5MeTGQbxEigFYKZt8RtTk62r.jpg"] |
| longitude               | 2.15133                                                                                                                                      |
| latitude                | 41.37770                                                                                                                                     |
| quiet                   | Gens tranquil                                                                                                                                |
| cleanliness             | Dolent                                                                                                                                       |
| accessibility           | Dolenta                                                                                                                                      |
| safety                  | Regular                                                                                                                                      |
| influence               | Yhbhd                                                                                                                                        |
| landmark                | question_removed                                                                                                                             |
| protection              | Frdyhn                                                                                                                                       |
| user_id                 | 9bd685aa-62f6-461a-8b39-8ddacc6e6fbe                                                                                                         |
| created_at              | 2024-06-18 10:49:57                                                                                                                          |
| updated_at              | 2024-06-18 10:49:57                                                                                                                          |
| deleted_at              | NULL                                                                                                                                         |
| temperature             | 27.05                                                                                                                                        |
| pressure                | 1013                                                                                                                                         |
| humidity                | 57                                                                                                                                           |
| wind_speed              | 7.72                                                                                                                                         |
| pleasant                | NULL                                                                                                                                         |
| chaotic                 | NULL                                                                                                                                         |
| vibrant                 | NULL                                                                                                                                         |
| uneventful              | NULL                                                                                                                                         |
| calm                    | NULL                                                                                                                                         |
| annoying                | NULL                                                                                                                                         |
| eventfull               | NULL                                                                                                                                         |
| monotonous              | NULL                                                                                                                                         |
| overall                 | NULL                                                                                                                                         |
| path                    | [{"lat":41.3777038,"lng":2.1513264}]                                                                                                          |

**Comment by OtariOboladzeSfC** [comment]
it still is not able to connect
