### ISSUE TITLE
update 'path' from varchar to text

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_dashboard#58]
this code was run on the database to modify 'path' column 'varchar' type into 'text' type: 

'ALTER TABLE soundcollect.observations MODIFY COLUMN `path` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'the user location will be saved here for every 10 seconds.';'

to do: update Laravel migration to reflect changes.

Observations path column varchar -> text

**Comment by OtariOboladzeSfC** [comment]
note: remove 'default()' when updating, other ways it will give error as TEXT has no default constraint.

so:
CHARSET - ok
COLLATE - ok
NOT NULL - ok
COMMENT - ok
DEFAULT - omit

**Comment by CarlosMillanSfC** [comment]
@OtariOboladzeSfC told me to leave this issue and work in #31 but also to forget this one because will not be done, or at least this is no longer mine. Tell me if I have misunderstood you @OtariOboladzeSfC pls

**Comment by OtariOboladzeSfC** [comment]
'Path' column needs to be completely removed from 'observations' table

**Comment by CarlosMillanSfC** [comment]
There is 10 observations that do not have the path setted in the table observations:

mysql> select count(distinct path) from observations;
+----------------------+
| count(distinct path) |
+----------------------+
|                  325 |
+----------------------+
1 row in set (0.01 sec)

mysql> select count(*) from observations;
+----------+
| count(*) |
+----------+
|      335 |
+----------+
1 row in set (0.03 sec)

@OtariOboladzeSfC 
so i remove the path column completely? Are we sure it is not used anywhere and we will not need those values never?
