### ISSUE TITLE
Filtrar por lugares con una influencia positiva en los estados de ánimo/emociones.

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#7]
Para esto de cada registro se tendrá en cuenta la pregunta sobre la percepción: ¿Los sonidos de este lugar influyen positivamente en su estado de ánimo/emociones?

Las categorías de este filtro serán las mismas opciones que hay en las respuestas. Es decir: Muy de acuerdo; de acuerdo; indeciso; en desacuerdo y muy en desacuerdo.

**Comment by TomasTubertSFC** [comment]
@OtariOboladzeSfC Necesitaría saber cual es la key de la observación que tiene este valor.
``
{
      "type": "observation",
      "id": "9b879c0b-a13c-46e9-8bf0-348ddb4c6286",
      "attributes": {
        "Leq": "118.88",
        "LAeqT": "103.93,114.83,114.6,115.32,114.9,108.08,103.84,99.14,100.46,101.42",
        "LAmax": "115.32",
        "LAmin": "99.14",
        "L90": "100.46",
        "L10": "115.32",
        "sharpness_S": "N/A",
        "loudness_N": "N/A",
        "roughtness_R": "N/A",
        "fluctuation_strength_F": "N/A",
        "images": [
          "https://soundcollectbucket.s3.eu-central-1.amazonaws.com/users/9b878a55-2141-47a4-84f3-a7fe4ded3550/LUD5xIuAbkGBPqwb5ZSpD8hRbaDxtqD8YLwjqErf.jpg"
        ],
        "latitude": "41.98867",
        "longitude": "2.81922",
        "quiet": "Bastant tranquil",
        "cleanliness": "Regular",
        "accessibility": "Molt bé",
        "safety": "De pas, caminant",
        "influence": "Neutre",
        "landmark": "Si",
        "protection": "Ja ho està la devesa en principi",
        "wind_speed": "9.26",
        "humidity": 52,
        "temperature": "13.79",
        "pressure": 997,
        "user_id": "9b878a55-2141-47a4-84f3-a7fe4ded3550",
        "created_at": "2024-03-10 10:43:28",
        "updated_at": "2024-03-10 10:43:28",
        "path": "[{\"start\": {\"lat\": 41,98867,\"lon\": 2,81922},\"end\": {\"lat\": 41,9890835142055,\"lon\": 2,81951508865649},\"parameters\": {\"L90\": 100,46,\"L10\":  115,32,\"Laeq\":  118,88,\"Lamin\":  99,14}},{\"start\": {\"lat\": 41,9888920115878,\"lon\": 2,8200745728552},\"end\": {\"lat\": 41,9890601404583,\"lon\": 2,8200948072658},\"parameters\": {\"L90\": 108,41983881788,\"L10\":  119,158022663598,\"Laeq\":  124,570107605437,\"Lamin\":  99,6696875862832}},{\"start\": {\"lat\": 41,9891395074109,\"lon\": 2,81981503551352},\"end\": {\"lat\": 41,9892829312339,\"lon\": 2,81971307137324},\"parameters\": {\"L90\": 110,249069358787,\"L10\":  117,09354491213,\"Laeq\":  125,919867437642,\"Lamin\":  106,86216964442}}]"
      },
``

**Comment by OtariOboladzeSfC** [comment]
@JohanaSfC @TomasTubertSFC  hay que revisar esta pregunta porque en la app no se pone como mupliple-choise si no es un campo de texto abierto:
![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/116548840/ed79b4c0-fb94-441e-90ea-3c3c78b4759a)

**Comment by CarlosMillanSfC** [comment]
@TomasTubertSFC por si aún sigues con la duda: es el el campo `influence`, que como dice oto es un texto libre por lo cual no se puede filtrar por categoría :/

Si miramos cuantos registros con ese campo diferente nos salen 198

**Comment by TomasTubertSFC** [comment]
Vale, gracias!

**Comment by JohanaSfC** [comment]
A día de hoy  (09/07/2024) no está implementado el cambio del tipo de esta pregunta en la app. 
Actualmente, está en modo campo de texto y debe ser una pregunta con opciones, tal cual se pone en el documento base. 

Por favor, @OtariOboladzeSfC actualiza el issue cundo este hecho el cambio en el back y en la BBDD para que se pueda implementar el filtro.

**Comment by TomasTubertSFC** [comment]
@OtariOboladzeSfC ayer implementó el cambio en la base de datos. Hoy he podido actualizar los filtros y así quedarían @JohanaSfC , dime si el orden es correcto.
![image](https://github.com/user-attachments/assets/ac3bfa1d-5b18-4a55-b62a-41186a8c3d4d)

Respecto a los datos, quedo a la espera de saber si el valor numérico corresponde con la palabra.
1: Molt d'acord
2: D'acord
3: Indecís
4: En desacord
5: Molt en desacord
Confirma me lo @OtariOboladzeSfC que es como lo has corregido en la base de datos. Sino, dime cual es el orden.

**Comment by OtariOboladzeSfC** [comment]
sí, es correcto: 

1: Molt d'acord
2: D'acord
3: Indecís
4: En desacord
5: Molt en desacord

**Comment by JohanaSfC** [comment]
Todo OK. Gracias Tomás
