### ISSUE TITLE
Crear polylines como observaciones

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/SoundCollect_dashboard#9]
Según reunión con @OtariOboladzeSfC 13/06. Ha comentado que las observaciones pasarán a ser polylines. Estás, tendrán valores y propiedades cada 10seg de grabación. Cada tramo, tendrá un color. La observación también tendrá un punto como marker.

Tendré que modificar tanto la sección 1 como la sección 2 ya que el JSON de datos me va a cambiar.

- [x] Modificación de datos de observaciones para mapa
- [x] Colorear segmentos
- [x] Dibujado de lineas en la sección 3
- [x] Dibujado de lineas en la sección 1
- [x] Obtención de la ID de la observación al clicar
- [x] Marcar la observación clicada

**Comment by TomasTubertSFC** [comment]
¿De qué van a depender los colores?
¿Puedo ver algún JSON de datos de una observación? 
¿El marker en que parte de la observación irá?

**Comment by OtariOboladzeSfC** [comment]
¿De qué van a depender los colores? - LAeq
¿Puedo ver algún JSON de datos de una observación? - actualizaré SwaggerHub API con JSON info 
¿El marker en que parte de la observación irá? - @JohanaSfC  necesitamos tu opinion

**Comment by TomasTubertSFC** [comment]
¿Qué colores se asignan a cada valor de LAeq? @OtariOboladzeSfC

**Comment by OtariOboladzeSfC** [comment]
![IMG_4751](https://github.com/ScienceForChange/sc_dashboard/assets/116548840/19d3d1a9-a28d-46ae-95aa-60973480e08b)

**Comment by OtariOboladzeSfC** [comment]
Más correcto sería decir: 80 es el max que se usara para visualizar las observaciones en el mapa, porque técnicamente un sonido se puede llegar hasta 140 dB

**Comment by almenarasfc** [comment]
@OtariOboladzeSfC no veo el LAeq en lo que devuelve la API, sí están LAeqt (que es un array) y Leq

![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/144032518/d6146484-e149-42f2-a09f-f3da69a34d41)

**Comment by OtariOboladzeSfC** [comment]
es 'Leq', que se modifico durante desarrollo como 'LAeq'
@almenarasfc
