### ISSUE TITLE
flask returnes added parameters

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_dashboard#90]
desde flask server he añadido 3 parametros mas que nesecitan ser incorporadas en la base de datos despues de analizar un audio:

este endpoint **soundcollectflask.com/audio_new/{number}** devuelve estos datos:

{
    "L10": 6.822255631991439,
    "L90": 4.887175575552149,
    "LAeqT": [
        4.887175575552149,
        6.822255631991439
    ],
    "Leq": 5.961612063032245,
    "Lmax": 6.822255631991439,
    "Lmin": 4.887175575552149,
    "fluctuation": 0.0003485516798868581,
    "loudness": 2.515,
    "sharpness": 1.2372802548735777
}

de lo cual 'fluctuation', 'loudness' y 'sharpness' son nuevos y Laravel tiene que guardar estos datos en base de datos.

![image](https://github.com/ScienceForChange/SoundCollect_dashboard/assets/116548840/95432fd4-9d31-4a10-aa0f-2d02d1b9482e)

falta un parametro mas que es 'roughness' que estamos a la espera de ICR.

@CarlosMillanSfC

**Comment by CarlosMillanSfC** [comment]
ok, una pregunta, cuántos decimales recojo de esos valores? De normal recogemos 2 pero viendo que el campo fluctuation tiene muchos decimales (**"fluctuation": 0.0003485516798868581,**) lo veo mal.

**Comment by CarlosMillanSfC** [comment]
Estoy a la espera a que se me responda el comentario anterior pero mientras dejo esta rama con los cambios que deberían ser.

**Comment by CarlosMillanSfC** [comment]
@OtariOboladzeSfC he preguntado esto muchas veces pero lo pregunto una última vez por aquí: hay posibilidad de tener acceso al código de qualud? me refiero a donde ellos calculan la gamificación ya directamente para usarlo de guía.

Gracias.

**Comment by OtariOboladzeSfC** [comment]
> ok, una pregunta, cuántos decimales recojo de esos valores? De normal recogemos 2 pero viendo que el campo fluctuation tiene muchos decimales (**"fluctuation": 0.0003485516798868581,**) lo veo mal.

ya he pedido a ICR definir la precisión de 'fluctuation'
